Repository Vladyslav-Team/backend, pull requests merged in 2023-05, with the labels that each got.

#140 Commented test for backend_#127
  src/test/java/com/softserve/skillscope/proof/ProofRepoTest.java
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
  src/test/java/com/softserve/skillscope/talent/TalentInfoRepoTest.java
  src/test/java/com/softserve/skillscope/talent/TalentInfoTest.java
Labels: bug, backEnd

#144 Configure Security (roles, authentication, hasRole, permitions) to work with Talent, Sponsor
  pom.xml
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/security/auth/JwtToken.java
  src/main/java/com/softserve/skillscope/security/auth/controller/AuthenticationController.java
  src/main/java/com/softserve/skillscope/security/auth/service/AuthenticationService.java
  src/main/java/com/softserve/skillscope/security/auth/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/security/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/security/config/UserDetailsImpl.java
  src/main/java/com/softserve/skillscope/sponsor/controller/SponsorController.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/user/Role.java
  src/main/java/com/softserve/skillscope/user/model/User.java
  src/main/resources/application.properties
Labels: backEnd, security

#145 Added annotations for swagger, so QA can see the endpoints
  src/main/java/com/softserve/skillscope/general/swagger/SwaggerConfiguration.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/security/auth/controller/AuthenticationController.java
  src/main/java/com/softserve/skillscope/sponsor/controller/SponsorController.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
Labels: backEnd, feature

#149 Fix edpoints for sign up/ sign in/ sign out Backend #147
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/security/auth/controller/SponsorAuthenticationController.java
  src/main/java/com/softserve/skillscope/security/auth/controller/TalentAuthenticationController.java
  src/main/java/com/softserve/skillscope/security/auth/service/AuthenticationService.java
  src/main/java/com/softserve/skillscope/security/auth/service/impl/AuthenticationServiceImpl.java
Labels: bug, mediumPriority, backEnd, security

#152 Add online payment using PayPal Backend #141
  pom.xml
  src/main/java/com/softserve/skillscope/security/config/PaypalConfiguration.java
  src/main/java/com/softserve/skillscope/security/payment/OrderStatus.java
  src/main/java/com/softserve/skillscope/security/payment/PayPalEndpoints.java
  src/main/java/com/softserve/skillscope/security/payment/controller/PaymentController.java
  src/main/java/com/softserve/skillscope/security/payment/model/CompletedOrder.java
  src/main/java/com/softserve/skillscope/security/payment/model/PaymentOrder.java
  src/main/java/com/softserve/skillscope/security/payment/service/PayPalService.java
  src/main/java/com/softserve/skillscope/security/payment/service/impl/PayPalServiceImpl.java
  src/main/java/com/softserve/skillscope/sponsor/controller/SponsorController.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorService.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorServiceImpl.java
  src/main/java/com/softserve/skillscope/user/model/UserProperties.java
  src/main/resources/application.properties
Labels: backEnd, feature

#154 Fix security Backend #148 newsecurity
  src/main/java/com/softserve/skillscope/general/mapper/UserMapper.java
  src/main/java/com/softserve/skillscope/general/mapper/UserMapperImpl.java
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/security/auth/controller/AuthenticationController.java
  src/main/java/com/softserve/skillscope/security/auth/controller/TalentAuthenticationController.java
  src/main/java/com/softserve/skillscope/security/auth/service/AuthenticationService.java
  src/main/java/com/softserve/skillscope/security/auth/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/security/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/security/config/UserDetailsImpl.java
  src/main/java/com/softserve/skillscope/security/payment/controller/PaymentController.java
  src/main/java/com/softserve/skillscope/sponsor/controller/SponsorController.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/resources/application-dev.properties
Labels: bug, highPriority, backEnd, security

#162 Add timer to task 150 to get new game for kudos and check if sponsor paid money to skip this timer#151 + Insert Sponsors#146
  src/main/java/com/softserve/skillscope/general/mapper/sponsor/impl/SponsorMapperImpl.java
  src/main/java/com/softserve/skillscope/general/mapper/talent/TalentMapper.java
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/security/auth/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/security/payment/OrdersRepository.java
  src/main/java/com/softserve/skillscope/security/payment/controller/PaymentController.java
  src/main/java/com/softserve/skillscope/security/payment/model/dto/CompletedOrder.java
  src/main/java/com/softserve/skillscope/security/payment/model/dto/PaymentOrder.java
  src/main/java/com/softserve/skillscope/security/payment/model/entity/Orders.java
  src/main/java/com/softserve/skillscope/security/payment/model/enums/OrderStatus.java
  src/main/java/com/softserve/skillscope/security/payment/model/enums/PayPalEndpoints.java
  src/main/java/com/softserve/skillscope/security/payment/service/PayPalService.java
  src/main/java/com/softserve/skillscope/security/payment/service/impl/PayPalServiceImpl.java
  src/main/java/com/softserve/skillscope/sponsor/controller/SponsorController.java
  src/main/java/com/softserve/skillscope/sponsor/model/entity/Sponsor.java
  src/main/java/com/softserve/skillscope/sponsor/model/entity/SponsorProperties.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorService.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V2/V8_4__Insert_sponsors.sql
  src/main/resources/db/migration/V2/V8_5__Create_Orders.sql
Labels: database, backEnd, 3.2.0

#165 Hot fix of "showAmountKudosOfProof" to handle when the sponsor id in kudos, when id is null
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
Labels: bug, highPriority, backEnd

#166 Hotfix #find all kudosed by sponsor
  src/main/java/com/softserve/skillscope/proof/ProofRepository.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
Labels: bug, highPriority, backEnd

#168 Added ability to view Skill on Proofs
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/security/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/skill/SkillRepository.java
  src/main/java/com/softserve/skillscope/skill/model/Skill.java
  src/main/java/com/softserve/skillscope/skill/model/SkillResponse.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V2/V8_6__Insert_skills.sql
Labels: backEnd

#170 Hotfix_#157(test)
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
Labels: bug

#171 Hotfix_#157(
  src/main/resources/db/migration/V2/V8_6__Insert_skills.sql
Labels: bug

#173 Add endpoint for get all skills(filter) backend_#169
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/security/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/skill/SkillRepository.java
  src/main/java/com/softserve/skillscope/skill/controller/SkillController.java
  src/main/java/com/softserve/skillscope/skill/model/entity/Skill.java
  src/main/java/com/softserve/skillscope/skill/model/response/AddSkillRequest.java
  src/main/java/com/softserve/skillscope/skill/model/response/SkillResponse.java
  src/main/java/com/softserve/skillscope/skill/service/SkillService.java
  src/main/java/com/softserve/skillscope/skill/service/impl/SkillServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
Labels: highPriority, backEnd

#180 Fixed bug with addSkills
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/skill/model/entity/Skill.java
  src/main/java/com/softserve/skillscope/skill/model/response/AddSkillRequest.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: bug

#182 Backend #178
  pom.xml
  src/main/java/com/softserve/skillscope/general/mapper/talent/TalentMapper.java
  src/main/java/com/softserve/skillscope/general/mapper/talent/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/skill/SkillRepository.java
  src/main/java/com/softserve/skillscope/skill/service/impl/SkillServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/TalentRepository.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/dto/GeneralTalent.java
  src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/user/model/UserProperties.java
  src/main/resources/application.properties
Labels: highPriority, backEnd

#189 Add ability to view amount of Kudos on Skills + change logic for showAmountKudosOfProof
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/kudos/KudosRepository.java
  src/main/java/com/softserve/skillscope/kudos/model/enity/Kudos.java
  src/main/java/com/softserve/skillscope/kudos/model/response/KudosResponse.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/skill/controller/SkillController.java
  src/main/java/com/softserve/skillscope/skill/model/entity/Skill.java
  src/main/java/com/softserve/skillscope/skill/service/SkillService.java
  src/main/java/com/softserve/skillscope/skill/service/impl/SkillServiceImpl.java
  src/main/resources/db/migration/V2/V8_8__Update_Kudos.sql
Labels: highPriority, database, backEnd

#193 Added ability to view OWN total amount of Kudoses
  src/main/java/com/softserve/skillscope/general/mapper/talent/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
  src/main/java/com/softserve/skillscope/talent/model/entity/Talent.java
Labels: highPriority, backEnd

#197 Add ability to view OWN the most kudosed Skills
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/response/TalentStatsResponse.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: highPriority, backEnd

#199 Qa #23
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/proof/service/impl/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/security/payment/service/impl/OrdersServiceImpl.java
  src/main/java/com/softserve/skillscope/security/payment/service/impl/PayPalServiceImpl.java
  src/main/java/com/softserve/skillscope/skill/model/response/MostKudosedSkillsResponse.java
  src/main/java/com/softserve/skillscope/sponsor/service/SponsorServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/user/service/impl/UserServiceImpl.java
Labels: bug, highPriority, backEnd, qa

#201 Add ability to view OWN the most Kudosed Proof#186
  src/main/java/com/softserve/skillscope/skill/service/impl/SkillServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/response/TalentStatsResponse.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: highPriority, backEnd

#203 Fixed find used by id to talent. backend_#186
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: bug

#202 Added flag "verified" for skills on talents
  src/main/java/com/softserve/skillscope/general/mapper/talent/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/skill/model/dto/SkillWithVerification.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
  src/main/resources/db/migration/V2/V8_10__Update_Skills.sql
Labels: lowPriority, feature

#204 Bug fix with code of verified.
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: bug, highPriority, backEnd

#205 Fixed problem with hide Proofs
  src/main/java/com/softserve/skillscope/talent/service/impl/TalentServiceImpl.java
Labels: bug, highPriority, backEnd

#209 Add ADMIN to delete proofs, talent and so on Backend #206
  src/main/java/com/softserve/skillscope/general/handler/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/general/handler/exception/generalException/ConflictException.java
  src/main/java/com/softserve/skillscope/general/handler/exception/generalException/ForbiddenRequestException.java
  src/main/java/com/softserve/skillscope/general/util/service/UtilService.java
  src/main/java/com/softserve/skillscope/general/util/service/impl/UtilServiceImpl.java
  src/main/java/com/softserve/skillscope/security/admin/controller/AdminController.java
  src/main/java/com/softserve/skillscope/security/admin/model/enums/AdminStatus.java
  src/main/java/com/softserve/skillscope/security/admin/service/AdminService.java
  src/main/java/com/softserve/skillscope/security/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/softserve/skillscope/security/auth/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/security/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/user/Role.java
  src/main/java/com/softserve/skillscope/user/UserRepository.java
Labels: highPriority, backEnd, security, feature

#210 Hotfix of admin
  src/main/java/com/softserve/skillscope/security/admin/service/impl/AdminServiceImpl.java
Labels: bug, backEnd

#211 Changed error to forbidden.
  src/main/java/com/softserve/skillscope/security/admin/service/impl/AdminServiceImpl.java
Labels: bug, backEnd
