Repository Vladyslav-Team/backend, pull requests merged in 2023-03, with the labels that each got.

#11 Initialize the SpringBoot frameWork
  .gitignore
  README.md
  pom.xml
  src/main/java/com/softserve/skillscope/SkillScopeApplication.java
  src/main/java/com/softserve/skillscope/talent/TalentController.java
  src/main/java/com/softserve/skillscope/talent/TalentRepository.java
  src/main/java/com/softserve/skillscope/talent/TalentService.java
  src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/model/entity/Talent.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoController.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoRepository.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoService.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application.properties
  src/test/java/com/softserve/skillscopebackend/WebApplicationTests.java
Labels: backEnd

#17 Hot-fix of the backend_#9 task with pom.xml and maven build adds
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/test/java/com/softserve/skillscope/WebApplicationTests.java
Labels: bug, backEnd

#20 Create .env file configuration and profiles for dev/prod/test branches#16
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: highPriority, backEnd

#35 Add pagination to the main page with talents
  src/main/java/com/softserve/skillscope/SkillScopeApplication.java
  src/main/java/com/softserve/skillscope/exception/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/exception/generalException/BadRequestException.java
  src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
  src/main/java/com/softserve/skillscope/talent/TalentController.java
  src/main/java/com/softserve/skillscope/talent/TalentService.java
  src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/model/dto/GeneralTalent.java
  src/main/java/com/softserve/skillscope/talent/model/entity/TalentFlashcard.java
  src/main/java/com/softserve/skillscope/talent/model/entity/TalentProperties.java
  src/main/resources/application.properties
  src/main/resources/data/data.sql
  src/test/java/com/softserve/skillscope/Talent/TestTalent.java
Labels: highPriority, backEnd

#39 Hotfix backend #4, added experience field, changed data.sql
  src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
  src/main/java/com/softserve/skillscope/talent/model/dto/GeneralTalent.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/data/data.sql
Labels: bug, backEnd
