Repository Vladyslav-Team/backend, pull requests merged in 2023-04, with the labels that each got.

#43 Code refactor, bug fixes, reverse pagination, local date solve issue, turned on prod settings for env file from devOps
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
  src/main/java/com/softserve/skillscope/mapper/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/talent/TalentController.java
  src/main/java/com/softserve/skillscope/talent/TalentRepository.java
  src/main/java/com/softserve/skillscope/talent/TalentService.java
  src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/model/response/GeneralTalentResponse.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoController.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoRepository.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoService.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application.properties
Labels: bug, backEnd

#41 Branch #38 login registration
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/config/TalentDetailsImpl.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationController.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationService.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/TalentRepository.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/entity/Talent.java
  src/main/java/com/softserve/skillscope/talent/model/request/RegistrationRequest.java
  src/main/java/com/softserve/skillscope/talent/model/response/JwtToken.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application.properties
  src/main/resources/data/data.sql
Labels: highPriority, backEnd

#46 Changed record field (bug fix)
  src/main/java/com/softserve/skillscope/talent/model/response/GeneralTalentResponse.java
Labels: bug, backEnd

#40 Add ability to view all talent information(profile) #6
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
  src/main/java/com/softserve/skillscope/mapper/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
Labels: backEnd

#53 Merge dev into main with stable version
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/softserve/skillscope/SkillScopeApplication.java
  src/main/java/com/softserve/skillscope/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/advice/TalentExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/config/TalentDetailsImpl.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationController.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationService.java
  src/main/java/com/softserve/skillscope/config/authentication/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/exception/generalException/BadRequestException.java
  src/main/java/com/softserve/skillscope/exception/generalException/ForbiddenRequestException.java
  src/main/java/com/softserve/skillscope/exception/generalException/UnauthorizedUserException.java
  src/main/java/com/softserve/skillscope/exception/talentException/TalentAlreadyExistsException.java
  src/main/java/com/softserve/skillscope/exception/talentException/TalentNotFoundException.java
  src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
  src/main/java/com/softserve/skillscope/mapper/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/talent/TalentRepository.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/dto/GeneralTalent.java
  src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
  src/main/java/com/softserve/skillscope/talent/model/entity/Talent.java
  src/main/java/com/softserve/skillscope/talent/model/entity/TalentProperties.java
  src/main/java/com/softserve/skillscope/talent/model/request/RegistrationRequest.java
  src/main/java/com/softserve/skillscope/talent/model/response/GeneralTalentResponse.java
  src/main/java/com/softserve/skillscope/talent/model/response/JwtToken.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/TalentInfoRepository.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/main/resources/data/data.sql
  src/test/java/com/softserve/skillscope/Talent/TestTalent.java
  src/test/java/com/softserve/skillscope/Talent/TestTalentInfo.java
  src/test/java/com/softserve/skillscope/WebApplicationTests.java
Labels: 1.1

#42 Add the ability to delete the talent's account
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/response/TalentResponse.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: backEnd

#57 Added /logout endpoint
  src/main/java/com/softserve/skillscope/authentication/AuthenticationController.java
  src/main/java/com/softserve/skillscope/authentication/AuthenticationService.java
  src/main/java/com/softserve/skillscope/authentication/AuthenticationServiceImpl.java
Labels: highPriority, backEnd, security

#65 Add and configure Flyway Backend #45
  .gitignore
  pom.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/main/resources/data/data.sql
  src/main/resources/db/migration/V1__Initdb.sql
  src/main/resources/db/migration/V2__Insert_talent.sql
  src/main/resources/db/migration/V3__Insert_talentInfo.sql
Labels: mediumPriority, database, backEnd

#66 Dev bugfix (h2 db solve problem)
  src/main/resources/application-prod.properties
Labels: bug, database, backEnd

#68 Fixed TestTalentInfo
  src/test/java/com/softserve/skillscope/Talent/TestTalentInfo.java
Labels: bug

#69 2.2. Add a method to view full information about Proof Backend #50
  src/main/java/com/softserve/skillscope/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/advice/TalentExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/authentication/AuthenticationServiceImpl.java
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/exception/proofException/ProofNotFoundException.java
  src/main/java/com/softserve/skillscope/mapper/proof/ProofMapper.java
  src/main/java/com/softserve/skillscope/mapper/proof/impl/ProofMapperImpl.java
  src/main/java/com/softserve/skillscope/mapper/talent/TalentMapper.java
  src/main/java/com/softserve/skillscope/mapper/talent/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/dto/FullProof.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/model/request/TalentEditRequest.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/resources/db/migration/V4__Insert_proof.sql
Labels: bug, mediumPriority, database, backEnd

#70 Create a connection between our backend and devops DB Backend #55
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: highPriority, database, backEnd

#71 Add the ability to display Proofs on the main page (with sort)
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/mapper/proof/ProofMapper.java
  src/main/java/com/softserve/skillscope/mapper/proof/impl/ProofMapperImpl.java
  src/main/java/com/softserve/skillscope/proof/ProofRepository.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/dto/GeneralProof.java
  src/main/java/com/softserve/skillscope/proof/model/entity/ProofProperties.java
  src/main/java/com/softserve/skillscope/proof/model/response/GeneralProofResponse.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V4__Insert_proof.sql
Labels: backEnd

#76 Added GeneralProof and GeneralProofResponse
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/mapper/proof/ProofMapper.java
  src/main/java/com/softserve/skillscope/mapper/proof/impl/ProofMapperImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/dto/GeneralProof.java
  src/main/java/com/softserve/skillscope/proof/model/response/GeneralProofResponse.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/resources/db/migration/V4__Insert_proof.sql
Labels: bug, backEnd

#97 Added swagger to project.
  pom.xml
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
Labels: backEnd

#108 Add Junit test for services, repo and controllers Backend #105
  src/test/java/com/softserve/skillscope/Talent/TestTalent.java
  src/test/java/com/softserve/skillscope/proof/ProofRepoTest.java
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
  src/test/java/com/softserve/skillscope/proof/TestProof.java
  src/test/java/com/softserve/skillscope/talent/TalentRepoTest.java
  src/test/java/com/softserve/skillscope/talent/TalentServiceTest.java
  src/test/java/com/softserve/skillscope/talent/TalentTest.java
  src/test/java/com/softserve/skillscope/talentInfo/TalentInfoRepoTest.java
  src/test/java/com/softserve/skillscope/talentInfo/TalentInfoTest.java
Labels: mediumPriority, backEnd, feature

#96 Validation for addProof and ability create Proof with null values
  src/main/java/com/softserve/skillscope/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/advice/ProofExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/exception/generalException/ValidationException.java
  src/main/java/com/softserve/skillscope/exception/proofException/ProofHasNullValue.java
  src/main/java/com/softserve/skillscope/mapper/proof/impl/ProofMapperImpl.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/ProofEditRequest.java
  src/main/java/com/softserve/skillscope/proof/model/dto/FullProof.java
  src/main/java/com/softserve/skillscope/proof/model/dto/GeneralProof.java
  src/main/java/com/softserve/skillscope/proof/model/dto/ProofCreationDto.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/model/entity/ProofProperties.java
  src/main/java/com/softserve/skillscope/proof/model/request/ProofRequest.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Initdb.sql
  src/main/resources/db/migration/V4__Insert_proof.sql
  src/main/resources/db/migration/V5__Update_proof.sql
Labels: bug, backEnd

#120 V2.6.0
  pom.xml
  src/main/java/com/softserve/skillscope/advice/GeneralExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/advice/ProofExceptionsControllerAdvice.java
  src/main/java/com/softserve/skillscope/config/SecurityConfiguration.java
  src/main/java/com/softserve/skillscope/exception/generalException/ValidationException.java
  src/main/java/com/softserve/skillscope/exception/proofException/ProofAlreadyPublishedException.java
  src/main/java/com/softserve/skillscope/exception/proofException/ProofHasNullValue.java
  src/main/java/com/softserve/skillscope/generalModel/GeneralResponse.java
  src/main/java/com/softserve/skillscope/mapper/proof/impl/ProofMapperImpl.java
  src/main/java/com/softserve/skillscope/mapper/talent/impl/TalentMapperImpl.java
  src/main/java/com/softserve/skillscope/proof/ProofRepository.java
  src/main/java/com/softserve/skillscope/proof/controller/ProofController.java
  src/main/java/com/softserve/skillscope/proof/model/dto/FullProof.java
  src/main/java/com/softserve/skillscope/proof/model/dto/GeneralProof.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/proof/model/entity/ProofProperties.java
  src/main/java/com/softserve/skillscope/proof/model/request/ProofRequest.java
  src/main/java/com/softserve/skillscope/proof/model/response/ProofResponse.java
  src/main/java/com/softserve/skillscope/proof/service/ProofService.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/controller/TalentController.java
  src/main/java/com/softserve/skillscope/talent/model/response/TalentResponse.java
  src/main/java/com/softserve/skillscope/talent/service/TalentService.java
  src/main/java/com/softserve/skillscope/talent/service/TalentServiceImpl.java
  src/main/java/com/softserve/skillscope/talentInfo/model/entity/TalentInfo.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Initdb.sql
  src/main/resources/db/migration/V4__Insert_proof.sql
  src/main/resources/db/migration/V5__Update_proof.sql
  src/main/resources/db/migration/V6__Update_proof_dateType.sql
  src/test/java/com/softserve/skillscope/Talent/TestTalent.java
  src/test/java/com/softserve/skillscope/proof/ProofRepoTest.java
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
  src/test/java/com/softserve/skillscope/proof/TestProof.java
  src/test/java/com/softserve/skillscope/talent/TalentRepoTest.java
  src/test/java/com/softserve/skillscope/talent/TalentServiceTest.java
  src/test/java/com/softserve/skillscope/talent/TalentTest.java
  src/test/java/com/softserve/skillscope/talentInfo/TalentInfoRepoTest.java
  src/test/java/com/softserve/skillscope/talentInfo/TalentInfoTest.java
Labels: 2.6.0

#122 3.1 Create new table Kudos in our DB Backend #113
  src/main/java/com/softserve/skillscope/kudos/KudosRepository.java
  src/main/java/com/softserve/skillscope/kudos/model/enity/Kudos.java
  src/main/java/com/softserve/skillscope/proof/model/entity/Proof.java
  src/main/java/com/softserve/skillscope/talent/model/entity/Talent.java
  src/main/resources/db/migration/V1__Initdb.sql
  src/test/java/com/softserve/skillscope/kudos/KudosRepoTest.java
  src/test/java/com/softserve/skillscope/proof/ProofTest.java
  src/test/java/com/softserve/skillscope/talent/TalentRepoTest.java
  src/test/java/com/softserve/skillscope/talent/TalentTest.java
Labels: highPriority, database, backEnd

#123 Hot fix for Backend #113 db
  src/main/resources/db/migration/V1__Initdb.sql
  src/main/resources/db/migration/V7__Create_kudos.sql
Labels: bug, database, backEnd

#130 Bugfix #67 (impossible creating and empty proof, double publish/hide proof)
  src/main/java/com/softserve/skillscope/proof/model/request/ProofRequest.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
Labels: bug, backEnd

#135 Hotfix #67 + feature for display kudos
  src/main/java/com/softserve/skillscope/proof/model/response/KudosResponse.java
  src/main/java/com/softserve/skillscope/proof/service/ProofServiceImpl.java
  src/main/java/com/softserve/skillscope/talent/model/request/RegistrationRequest.java
Labels: bug, backEnd, feature
